version: '3.8'

services:
  ifood.reviews.api:
    image: ${DOCKER_REGISTRY-}ifoodreviewsapi
    build:
      context: .
      dockerfile: Presentation/iFood.Reviews.Api/Dockerfile
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example 
